### ISSUE TITLE
Error when Source Cvs kbskit0.4

### ISSUE THREAD

**Issue by liufujun135** [open-power/amester#3]
The error info is as following. I can access kbskit.cvs.sourceforge.net through browser. Is there some error on this command(/usr/bin/cvs -d :pserver:anonymous@kbskit.cvs.sourceforge.net:/cvsroot/kbskit -z3 co -P -d kbskit0.4 -r kbskit_0_4 kbskit) or what other method I can get this file(kbsmk8.6-bi)?

Thanks a lot.

=== Source Cvs kbskit0.4
/usr/bin/cvs -d :pserver:anonymous@kbskit.cvs.sourceforge.net:/cvsroot/kbskit -z3 co -P -d kbskit0.4 -r kbskit_0_4 kbskit
cvs [checkout aborted]: connect to kbskit.cvs.sourceforge.net(216.34.181.112):2401 failed: Connection timed out
child process exited abnormally
=== Require error: kbskit0.4
missing sources of package 'kbskit0.4'
Error in execution of 'install kbskit8.6':
=== Package failed for: kbskit0.4
Require failed for: kbskit0.4
cp package/kbs/build_linux-gnu_x86_64/bin/kbsmk8.6-bi package
cp: cannot stat ‘package/kbs/build_linux-gnu_x86_64/bin/kbsmk8.6-bi’: No such file or directory
make[1]: **\* [package/kbsmk8.6-bi] Error 1
make[1]: Leaving directory `/home/fujun_liu/amester'
make: **\* [default] Error 2_**

**Comment by lefurgy** [comment]
I believe the failure to connect to sourceforge.net is intermittent. It worked fine for me today. Please try again.  If you can checkout the code another way, you can put it into the package/kbs/sources/kbskit0.4 directory and then the download will not be required.
