### ISSUE TITLE
Can't build on amester on Power8 running Ubuntu 15 (pcc64le)

### ISSUE THREAD

**Issue by davidcarver** [open-power/amester#4]
cat: /etc/issues: No such file or directory
dcarver@p8capi3:~/amester/amester-master$ cat /etc/issue
Ubuntu 15.04 \n \l

dcarver@p8capi3:~/amester/amester-master$ uname -a
Linux p8capi3 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:54:18 UTC 2015 ppc64le ppc64le ppc64le GNU/Linux
dcarver@p8capi3:~/amester/amester-master$ ./configure
**checking build system type... Invalid configuration `ppc64le-unknown-linux-gnu': machine`ppc64le-unknown' not recognized
configure: error: /bin/bash ./config.sub ppc64le-unknown-linux-gnu failed**
dcarver@p8capi3:~/amester/amester-master$

**Comment by davidcarver** [comment]
Diff of config.sub to recognize pcc64le

root@p8capi3:/home/00108/dcarver/amester/amester-master# diff config.sub config.sub.orig
 720c720
 <       ppcle | ppc64le | powerpclittle | ppc-le | powerpc-little)

---

> ```
>   ppcle | powerpclittle | ppc-le | powerpc-little)
> ```
> 
>  723c723
>  <       ppcle-\* | ppc64le-\* | powerpclittle-*)
> 
> ---
> 
> ```
>   ppcle-* | powerpclittle-*)
> ```

**Comment by baileysh** [comment]
I am new owner,, did you get your resolution ?
from what I have learned, this tool was for intel x86 linux from version 6 onward.

I have to take a stance of PPC not supported at this time.  Putting under future work.
