### ISSUE TITLE
Why does amester need to rebuild tcl and tk?

### ISSUE THREAD

**Issue by davidcarver** [open-power/amester#5]
Why does amester need to download and rebuild tcl8.6 and tk8.6 ?  Shouldn't this be a dependency?

root@p8capi3:/home/00108/dcarver/amester/amester-master# apt-cache search ^tk8.6
tk8.6 - Tk toolkit for Tcl and X11 v8.6 - windowing shell
tk8.6-blt2.5 - graphics extension library for Tcl/Tk - library
tk8.6-dev - Tk toolkit for Tcl and X11 v8.6 - development files
tk8.6-doc - Tk toolkit for Tcl and X11 v8.6 - manual pages
root@p8capi3:/home/00108/dcarver/amester/amester-master# apt-cache search ^tcl8.6
tcl8.6 - Tcl (the Tool Command Language) v8.6 - shell
tcl8.6-dev - Tcl (the Tool Command Language) v8.6 - development files
tcl8.6-doc - Tcl (the Tool Command Language) v8.6 - manual pages
tcl8.6-tdbc - Tcl Database Connectivity
tcl8.6-tdbc-mysql - Tcl Database Connectivity
tcl8.6-tdbc-odbc - ODBC driver for the Tcl Database Connectivity
tcl8.6-tdbc-postgres - Tcl Database Connectivity
tcl8.6-tdbc-sqlite3 - Tcl Database Connectivity

**Comment by baileysh** [comment]
This compiles tcl and dependencies like tk into the executable.
1) this does not have to be installed on system then.
2) allows the running of scripts under this executable, like the examples section.
