### ISSUE TITLE
No axis info in graph window?

### ISSUE THREAD

**Issue by kyle-ibm** [open-power/amester#7]
<img width="336" alt="screen shot 2016-08-08 at 11 35 53 am" src="https://cloud.githubusercontent.com/assets/17852056/17468665/addad26c-5d5c-11e6-958d-927b68643133.png">

Did I miss installing some package to get the graphing function to work properly? The graphing function not very useful without the axis information.
Running on an x86 Ubuntu 14.04.4 LTS with kernel 4.2.0-41-generic

**Comment by lefurgy** [comment]
Perhaps it could be related to the fonts installed on your system.  Do you have courier installed? The axis font is defined as "public variable axisfont {-family courier -size 14}".

**Comment by kyle-ibm** [comment]
Thanks for the pointer. My LCB only has courier 10 pitch and courier new installed. 
I just changed all "courier" references in files sensor_2_24.itcl and sensor_2_27.itcl to "courier new" and recompiled.

Graph titles and axis show up now.
